version: '3.8'

services:

  app:
    build: .
#    container_name: rest-app
    ports:
      - "8080:8080"
#    depends_on:
#      - postgres
    networks:
      - student-ka-net

  postgres:
    image: postgres:latest
#    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: telusko
      POSTGRES_USER: aditya
      POSTGRES_PASSWORD: 2357
    ports:
      - "5433:5432"
    networks:
      - student-ka-net


networks:
  student-ka-net:
    driver: bridge